### PR TITLE
Create MasterYoda_Castle.jason

### PR DESCRIPTION
**Pull request by Jerizu**
Jason file for a simple castle base create using no mods, so this one should not have any troubles to render

### CODE REVIEW

**Comment by charliebanks** [comment]
A couple of things.

1. Why are you calling it ".jason"? It should be ".json". The base builder plugin should already name this correctly for you when you save a preset.
2. What you're submitting is the entire base and not a preset. In order to create a preset please use the "Save Preset" option in the part list area of the tools, then you can locate the exact .json file within your folders and submit that.

**Comment by charliebanks** [comment]
Hey @Jerizu , did you accidentally remove the files? The latest commit indicates a deletion and there are no more file changes for this request.

Feel free to attach the files here and I can try and sort it out for you :)

**Comment by Jerizu** [comment]
> Hey @Jerizu , did you accidentally remove the files? The latest commit indicates a deletion and there are no more file changes for this request.
> 
> Feel free to attach the file and the image here and I can try and sort it out for you :)

No, that was on purpose, as you said I saved the file in the wrong way, so I deleted, I will upload again soon, but I noticed some issues with the building as well, I will fix it first and upload here, that's why I tried to delete the file

**Comment by Jerizu** [comment]
I apologize for the inconvenience, I don't have much experience using GitHub

**Comment by djmonkeyuk** [comment]
@Jerizu going to close this request. I know this response is super delayed but if you'd like to show off any presets in a more friendly way than you can find a community of builders in the Discord, just send me a message if you're interested :)

**Pull request closed without merging**
